name: aspnet-ci
on: [push]
jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5
      - run: ./src/test/dotnet test
      - run: ./src/app/dotnet test
