name: CI-NET

on: [push]

jobs:
  contrucao:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/app/app.csproj
    - name: Restore Test
      run: dotnet restore ./src/test/test.csproj
      
    - name: Build
      run: dotnet build --no-restore ./src/app/app.csproj
    - name: Test
      run: dotnet test  --verbosity normal ./src/test/test.csproj