name: CI-NET

on:
  pull_request:
    branches:
    - develop

jobs:
  check-application:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/app/app.csproj
    - name: Restore Test
      run: dotnet restore ./src/test/test.csproj
      
    - name: Build
      run: dotnet build --no-restore ./src/app/app.csproj
    - name: Test
      run: dotnet test  --verbosity normal ./src/test/test.csproj

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push 2
      uses: docker/build-push-action@v2
      with:
        context: . 
        push: true
        tags: dkendy/app:latest/